name: build , test and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the GitHub repo on the runners
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Run program dependencies
        run: npm install

      - name: Run integration tests
        run: npm test

  security_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Clone the GitHub repo on the runners
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Run program dependencies
        run: npm install

      - name: Run secutity tests
        run: npm audit

  deploy:
    runs-on: ubuntu-latest
    needs: security_tests
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_TOKEN }}
